// Generates dist/sw.js after `astro build`.
//
// Strategy (per design decision): PRECACHE EVERYTHING. The site is static and
// small over the wire (~10MB gzipped for all 587 section pages + assets), so we
// list every built file and have the service worker cache them all on install.
// After that the whole manual works offline, including never-visited sections.
//
// Hand-rolled (no @vite-pwa/astro dependency). The only build-time magic we need
// is (a) enumerating the files to precache and (b) a content hash so the cache
// name changes exactly when content changes — that's our cache-busting.
import { readdirSync, statSync, readFileSync, writeFileSync, createReadStream } from 'node:fs';
import { join, relative, posix } from 'node:path';
import { createHash } from 'node:crypto';

const DIST = new URL('../dist/', import.meta.url).pathname;

// Files we never want to precache or serve from the SW. search.json is the
// full-text index: large and only needed if you actually search, so it's kept
// out of the install precache and instead lazy-fetched + runtime-cached on the
// first ⌘K (see src/scripts/search.ts).
const EXCLUDE = new Set(['sw.js', 'CNAME', '.nojekyll', 'search.json']);

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const files = walk(DIST);

// Map an absolute dist path to the URL path the browser will request.
// Astro is configured with build.format:'directory', so `foo/index.html` is
// served at `/foo` (and the root index.html at `/`).
function toUrl(abs) {
  let rel = posix.normalize(relative(DIST, abs).split(/[\\/]/).join('/'));
  if (rel === 'index.html') return '/';
  if (rel.endsWith('/index.html')) return '/' + rel.slice(0, -'/index.html'.length);
  return '/' + rel;
}

const urls = [];
const hash = createHash('sha256');
for (const abs of files.sort()) {
  const rel = relative(DIST, abs).split(/[\\/]/).join('/');
  if (EXCLUDE.has(rel)) continue;
  urls.push(toUrl(abs));
  // Hash path + bytes so the cache version is fully content-addressed.
  hash.update(rel);
  hash.update(readFileSync(abs));
}

const version = hash.digest('hex').slice(0, 12);

// De-dupe (a directory page and its index.html can both map to the same URL).
const precache = [...new Set(urls)].sort();

const sw = `// AUTO-GENERATED by scripts/build-sw.mjs — do not edit by hand.
// Precaches the entire static site so the manual works fully offline.
const VERSION = ${JSON.stringify(version)};
const CACHE = 'globway-' + VERSION;
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Add in batches with allSettled so one failed asset can't abort the whole
    // install (unlike cache.addAll which is atomic). Missing assets just won't
    // be available offline; the rest still install.
    const BATCH = 50;
    for (let i = 0; i < PRECACHE.length; i += BATCH) {
      const slice = PRECACHE.slice(i, i + BATCH);
      await Promise.allSettled(slice.map((u) => cache.add(new Request(u, { cache: 'reload' }))));
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith('globway-') && k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});

// GitHub Pages 301-redirects directory paths (/p3 -> /p3/), so a precached page
// stored via cache.add() followed that redirect: its Response carries
// redirected:true and a query-stripped url (/p3/). Astro's SPA router honours
// response.redirected and would rewrite /p3?r=1 to /p3/, dropping the ?r= / ?p=
// the deck reader (random draw, card permalinks) depends on. Hand back a clean
// copy so the response reports no redirect and the requested URL+query stands.
function cleanRedirect(res) {
  if (!res.redirected) return res;
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers: res.headers });
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;                      // never touch writes
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;       // Supabase etc. -> network

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req, { ignoreSearch: true });
    if (cached) {
      // Cache-first (content is versioned), but refresh in the background so a
      // returning online user picks up the latest on the *next* visit.
      event.waitUntil((async () => {
        try {
          const fresh = await fetch(req);
          if (fresh && fresh.ok) await cache.put(req, fresh.clone());
        } catch {}
      })());
      return cleanRedirect(cached);
    }
    try {
      const fresh = await fetch(req);
      if (fresh && fresh.ok && fresh.type === 'basic') await cache.put(req, fresh.clone());
      return cleanRedirect(fresh);
    } catch {
      // Offline and uncached: for a page navigation, fall back to the app shell.
      if (req.mode === 'navigate') {
        const shell = await cache.match('/', { ignoreSearch: true });
        if (shell) return shell;
      }
      return new Response('Offline and not cached.', { status: 503, statusText: 'Offline' });
    }
  })());
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`[build-sw] wrote dist/sw.js — version ${version}, ${precache.length} precached URLs`);
